name: Technology Stack

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  profile_stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gleich/profile_stack@master
